name: Rust

on:
  push:
    branches: [ "master", "test" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: echo 123 > app.txt

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: app.txt
        path: ./app.txt
